# Создание объектов для хранения данных в Python

**Дисциплина:** Введение в анализ больших данных  
**Задание 1**

В Python для анализа данных наиболее часто используются библиотеки:
- **NumPy** — работа с массивами и матрицами (быстрые вычисления)
- **Pandas** — работа с таблицами (DataFrame) и одномерными структурами (Series)
- Встроенные типы Python: `list`, `tuple`, `dict`

В этой тетради мы разберём основные классы, объекты и методы, которые потребуются для выполнения Задания 1, и приведём решения всех пунктов задания на Python.

## 0. Установка и импорт необходимых библиотек

Рекомендуется выполнять код в Jupyter Notebook / Google Colab / VS Code.

In [1]:
# Если библиотеки ещё не установлены, раскомментируйте строки ниже:
# !pip install numpy pandas

import numpy as np
import pandas as pd

---
## 1. Векторы

Вектор — основная одномерная структура данных.



### Основные способы создания «векторов»:

In [22]:
# 1.1 Создание вектора S1 со значениями от 1 до 10

S1_list = list(range(1, 10))
print("Список:", S1_list)

Список: [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
# 1.2 Вектор S2 от 1 до 10 с шагом 0.5

S2 = np.arange(1, 10, 0.5)
print("S2 (arange):", S2)

S2 (arange): [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]

In [24]:
# 1.3 Объединение векторов S1 и S2 в вектор S

S = np.concatenate([S1, S2])
print(S)

[1.  2.  3.  4.  5.  1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.
 7.5 8.  8.5 9.  9.5]

In [30]:
# 1.4 Вывести 1-е, 2-е и 3-е значения вектора S

print("Элементы 3, 4, 5:", S[[2, 3, 4]])

Элементы 3, 4, 5: [3. 4. 5.]

In [31]:
# 1.5 Выбрать только первое и четвёртое значения вектора S

print("1-й и 4-й элементы:", S[[0, 3]])

1-й и 4-й элементы: [1. 4.]

---
## 2. Таблицы данных (DataFrame)

В R основная табличная структура — `data.frame`.

В Python — **`pandas.DataFrame`**.

Это самый важный объект для анализа данных.

In [40]:
# 2.1 Создание векторов (столбцов)
cities = ["Washington", "New-York", "London", "Paris", "Tokyo", "Osaka"]
sex = [['male', 'female'],['male', 'female'],['male', 'female'],['male', 'female'],['male', 'female'],['male', 'female']]
sex_vec2 = [[120, 130], [240,250], [160, 450], [204,270], [587, 652], [201,321]]

In [54]:
# 2.3 Создание таблицы EXAM с помощью pd.DataFrame


CITY = pd.DataFrame({
    "cities": cities,
    "sex": sex,
    "number": sex_vec2
})

CITY

       cities             sex      number
0  Washington  [male, female]  [120, 130]
1    New-York  [male, female]  [240, 250]
2      London  [male, female]  [160, 450]
3       Paris  [male, female]  [204, 270]
4       Tokyo  [male, female]  [587, 652]
5       Osaka  [male, female]  [201, 321]

In [55]:
# 2.4 Просмотр структуры таблицы

print("Информация о таблице:")
CITY.info()

print("\nТипы столбцов:")
print(CITY.dtypes)

print("\nРазмерность (строки, столбцы):", CITY.shape)

Информация о таблице:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cities  6 non-null      object
 1   sex     6 non-null      object
 2   number  6 non-null      object
dtypes: object(3)
memory usage: 272.0+ bytes

Типы столбцов:
cities    object
sex       object
number    object
dtype: object

Размерность (строки, столбцы): (6, 3)

In [56]:
# 2.5 Имена переменных (столбцов)

print(CITY.columns.tolist())

['cities', 'sex', 'number']

In [57]:
# 2.6 Извлечь элементы 1–3 из столбца Points

print(CITY["number"].iloc[0:3])

# альтернативы:
# EXAM.Points.iloc[0:3]
# EXAM.loc[0:2, "Points"]   # .loc использует метки (здесь совпадают с индексами)

0    [120, 130]
1    [240, 250]
2    [160, 450]
Name: number, dtype: object

In [60]:
CITY

       cities             sex      number
0  Washington  [male, female]  [120, 130]
1    New-York  [male, female]  [240, 250]
2      London  [male, female]  [160, 450]
3       Paris  [male, female]  [204, 270]
4       Tokyo  [male, female]  [587, 652]
5       Osaka  [male, female]  [201, 321]

In [63]:
# 2.7 Все значения баллов, превышающие 50


print(CITY["number"][1] > 10000)

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
# 2.8 Все значения баллов по математике


print(EXAM[EXAM["Subject"] == "Math"])

# или только числа:
print("\nБаллы по математике:")
print(EXAM.loc[EXAM["Subject"] == "Math", "Points"])

In [12]:
# 2.9 Первые и последние строки


print("Первые 3 строки:")
display(EXAM.head(1))

print("\nПоследние 2 строки:")
display(EXAM.tail(3))

Первые 3 строки:

   Names Subject  Points
0  Name1    Math      60

Последние 2 строки:

   Names  Subject  Points
3  Name2  Physics      10
4  Name3     Math      67
5  Name3  Physics      86

### Ключевые методы и атрибуты DataFrame
| Метод / атрибут | Описание |
|-----------------|----------|
| `.head(n)`, `.tail(n)` | первые / последние n строк |
| `.info()` | структура, типы, пропуски |
| `.describe()` | описательная статистика |
| `.shape`, `.columns`, `.index` | размер, имена столбцов, индексы |
| `.loc[]`, `.iloc[]` | доступ по меткам / по позициям |
| `df[условие]` | фильтрация строк |
| `df["col"]` или `df.col` | выбор столбца (Series) |
| `pd.concat()`, `pd.merge()` | объединение таблиц |

---
## 3. Матрицы

В R матрица — двумерный массив чисел.

В Python основной инструмент — **`numpy.ndarray`** с `ndim == 2`.

In [13]:
# 3.1 Создание матрицы размерности 2×8


m1 = np.arange(1, 7).reshape(2, 3)   # 16 элементов → 2 строки × 8 столбцов
print("Матрица 2×3:")
print(m1)
print("Форма:", m1.shape)

Матрица 2×3:
[[1 2 3]
 [4 5 6]]
Форма: (2, 3)

In [14]:
# 3.3 Транспонирование матрицы


m2 = m1.T
print("Транспонированная матрица (3×2):")
print(m2)
print("Форма:", m2.shape)

Транспонированная матрица (3×2):
[[1 4]
 [2 5]
 [3 6]]
Форма: (3, 2)

In [15]:
# 3.4 Квадратная матрица и определитель

square = np.array([[1, 2],
                   [3, 4]])
print("Квадратная матрица:")
print(square)

det = np.linalg.det(square)
print("Определитель:", det)

Квадратная матрица:
[[1 2]
 [3 4]]
Определитель: -2.0000000000000004

### Полезные операции с матрицами NumPy
- `A @ B` или `np.dot(A, B)` — матричное умножение
- `A * B` — поэлементное умножение
- `np.linalg.inv(A)` — обратная матрица
- `np.linalg.eig(A)` — собственные значения и векторы
- `A.reshape(...)`, `A.ravel()`, `A.flatten()`

---
## 4. Многомерные массивы

В R `array()` позволяет создавать массивы любой размерности.

В Python — тот же `numpy.ndarray`.

In [16]:
# 4.1 Массив из 24 элементов

# Создадим массив размерности (3, 2, 4) — 3×2 матрицы, 4 «слоя»
M = np.arange(1, 13).reshape(3, 2, 2)
print("Массив M формы", M.shape)
print(M)

# Альтернатива: явно через np.array и reshape

Массив M формы (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

In [17]:
# 4.2 Проверка, является ли объект массивом


print("Является ли M ndarray?", isinstance(M, np.ndarray))
print("Количество измерений (ndim):", M.ndim)
print("Форма:", M.shape)
print("Общее число элементов:", M.size)

Является ли M ndarray? True
Количество измерений (ndim): 3
Форма: (3, 2, 2)
Общее число элементов: 12

---
## 5. Списки

В R список (`list`) может содержать элементы разных типов и длин.

В Python:
- обычный `list` — упорядоченная коллекция
- `dict` — именованная коллекция (часто ближе к R-списку с именами)

In [18]:
# 5.1 Создание списка L1: числа от 1 до 6 + TRUE/FALSE три раза


numbers = list(range(1, 5))
full_name = ["ФИО"] * 4

L1 = [numbers, full_name]          # обычный список списков
# или
L1_dict = {
    "integers": numbers,
    "full_name": full_name
}

print("L1 (list):")
print(L1)

print("\nL1_dict:")
print(L1_dict)

L1 (list):
[[1, 2, 3, 4], ['ФИО', 'ФИО', 'ФИО', 'ФИО']]

L1_dict:
{'integers': [1, 2, 3, 4], 'full_name': ['ФИО', 'ФИО', 'ФИО', 'ФИО']}

---
## 6. Факторы (категориальные переменные)

В R `factor` — специальный тип для категориальных данных с фиксированными уровнями (levels).

В Python / Pandas — **`pandas.Categorical`** или столбец с `dtype="category"`.

In [19]:
# 6.1 Вектор из 6 объектов трёх классов: Low, Medium, High → фактор

answers = ["Low", "Medium", "High", "Low", "Medium", "High"]

# Создание Categorical
f1 = pd.Categorical(answers, categories=["Low", "Medium", "High"])
print(f1)
print("Уровни (categories):", f1.categories.tolist())
print("Коды:", f1.codes)

['Low', 'Medium', 'High', 'Low', 'Medium', 'High']
Categories (3, object): ['Low', 'Medium', 'High']
Уровни (categories): ['Low', 'Medium', 'High']
Коды: [0 1 2 0 1 2]

In [ ]:
# Использование в DataFrame
df_cat = pd.DataFrame({"answer": answers})
df_cat["answer"] = df_cat["answer"].astype("category")
print(df_cat.dtypes)
print(df_cat["answer"])

### Зачем нужны категории?
- Экономия памяти
- Возможность задать порядок (ordered categorical)
- Корректная работа многих статистических и ML-методов

---
## 7. Фрейм данных (ещё раз про DataFrame)

Пункт 7 задания — создание data.frame из разнотипных векторов, включая factor.

In [20]:
# 7.1 Создание фрейма F

k = ["x", "y", "z", "y", "z", "x"]
m = [(i % 3 == 0) for i in range(1, 7)]          # True/False
l = pd.Categorical(["true", "false", "empty", "empty", "false", "empty"],
                   categories=["true", "false", "empty"])

F = pd.DataFrame({
    "k": k,
    "m": m,
    "l": l
})

print(F)
print("\nТипы столбцов:")
print(F.dtypes)

   k      m      l
0  x  False   true
1  y  False  false
2  z   True  empty
3  y  False  empty
4  z  False  false
5  x   True  empty

Типы столбцов:
k      object
m        bool
l    category
dtype: object